"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# SECURITY & DEBUG
# ==============================

# Di production WAJIB pakai SECRET_KEY dari environment
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-ye7cfz9^6-%*gb18s$9_mvd2ba@059e!+abz($7j7z!#pz3%y8"  # fallback dev
)

DEBUG = os.environ.get("DEBUG", "False") == "True"

# Di Render nanti isi: ALLOWED_HOSTS=kyynime-backend.onrender.com,kyynime.vercel.app
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# ==============================
# APPS
# ==============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "api",
]

# ==============================
# MIDDLEWARE
# ==============================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Whitenoise untuk serve static di Render
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ==============================
# CORS
# ==============================

# Mode dev (lokal)
LOCAL_CORS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

# Di Render, nanti set env CORS_ALLOWED_ORIGINS="https://kyynime.vercel.app"
ENV_CORS = os.environ.get("CORS_ALLOWED_ORIGINS", "")

if ENV_CORS:
    CORS_ALLOWED_ORIGINS = ENV_CORS.split(",")
else:
    # fallback buat lokal
    CORS_ALLOWED_ORIGINS = LOCAL_CORS

# ==============================
# URLS & WSGI
# ==============================

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# ==============================
# DATABASE
# ==============================

# Default: sqlite (buat lokal)
default_sqlite = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}

# Kalau ada DATABASE_URL (di Render), pakai Postgres
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,  # kalau nanti pakai SSL bisa dibuat True
        )
    }
else:
    DATABASES = {"default": default_sqlite}

# ==============================
# PASSWORD VALIDATION
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==============================
# I18N
# ==============================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ==============================
# STATIC FILES
# ==============================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ==============================
# CACHING
# ==============================

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "kyynime-jikan-cache",
        "TIMEOUT": 3600,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

# ==============================
# LOGGING
# ==============================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
